### ISSUE TITLE
PGSQL_VERSION_DEFAULT backwards change from 2016Q4 to 2017Q1 / 2017Q2

### ISSUE THREAD

**Issue by drscream** [joyent/pkgbuild#12]
The pkgoption `PGSQL_VERSION_DEFAULT` changed between 2016Q4 to 2017Q1 and 2017Q2 backwards from `96` to `94`. I would like to ask if this is intended or what is the exact reason for this?

Thanks a lot.

**Comment by jperkin** [comment]
Oh, good spot, sorry about that. It was unintended. The change was made to the 2016Q4 configuration but not to the trunk configuration, so when 2017Q1 was created from trunk the change was missed.

We'll need to leave 2017Q1 and 2017Q2 alone, but I will change trunk so that 2017Q3 and onwards correctly use 96.

**Comment by jperkin** [comment]
Looks like we were missing a couple of other options too. Thanks!
